### ISSUE TITLE
When can we expect a stable release?

### ISSUE THREAD

**Issue by jayaram9877** [Allan-Nava/nakama-flutter#3]

**Comment by Allan-Nava** [comment]
Hi @jayaram9877 , wanna help me?

**Comment by jayaram9877** [comment]
> Hi @jayaram9877 , wanna help me?

Hi @Allan-Nava , I don't have experience in developing packages, if I can get a little push at the start I'll try my best.

**Comment by Allan-Nava** [comment]
> > Hi @jayaram9877 , wanna help me?
> 
> Hi @Allan-Nava , I don't have experience in developing packages, if I can get a little push at the start I'll try my best.

Yess the main problem is to understand how to integrate the grpc proto stuff

like this bash script: https://github.com/Allan-Nava/nakama-flutter/blob/main/protos/generate.sh

**Comment by Allan-Nava** [comment]
@jayaram9877 this is the stable version: https://github.com/obrunsmann/flutter_nakama

**Comment by Allan-Nava** [comment]
It may stable right now

**Comment by lchenneberg** [comment]
Hello, Could you provide a documentation to integrate this package in a project?
